routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});



Route::resource('personas', 'PersonaController');


/*Route::get('/',[
    'as' => 'persona',
    'uses' => 'PersonaController'
]);*/

app/Persona.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    protected $table = 'personas';
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PersonaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Persona;

class PersonaController extends Controller
{
    public function index() {
$personas = Persona::get();
return view('personas.index')->with('personas', $personas);
}
    
public function create() {
return view('personas.create');
}
    
public function store(Request $request) {
$persona = new Persona;
$max = Persona::get()->max('id');
$persona->id = $max + 1;
$persona->nombre = $request->input('nombre');
$persona->save();
return redirect()->route('personas.index');
}
    
    public function edit($id) {
$persona = Persona::find($id);
return view('personas.edit')->with('persona', $persona);
}
    
public function update(Request $request, $id) {
$persona = Persona::find($id);
$persona->id = $id;
$persona->nombre = $request->input('nombre');
$persona->save();
return redirect()->route('personas.index');
}
    
public function destroy($id) {
Persona::destroy($id);
return redirect()->route('personas.index');
}
   
public function show($id) {
   $persona = Persona::find($id);
   return View::make('persona.show')->with('persona', $persona);
}
    
}

resources/views/personas.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AGENDA</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript"></script>
@section('styles_laravel')
{!! Html::style('css/bootstrap.css') !!}
{!! Html::style('css/datatable-bootstrap.css') !!}
<!-- Fonts -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
@show
@yield('my_styles')
</head>
<body>
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
@yield('content')
</div>
</div>
</div>
<!-- Scripts -->
{!! Html::script('js/jquery.js') !!}
{!! Html::script('js/jquery.dataTables.js') !!}
{!! Html::script('js/bootstrap.min.js') !!}
{!! Html::script('js/datatable-bootstrap.js') !!}
<script>
$(document).ready(function () {
$('#MyTable').dataTable();
});
</script>
@yield('my_scripts')
</body>
</html>

resources/views/personas/create.blade.php
@extends('personas')
@section('content')
<!--<form action="{{route('personas.store')}}" method ="POST">-->
{!! Form::open(['route' => 'personas.store', 'method' => 'POST']) !!}
<!--</form>-->
@include('personas.partials.fields')
<button type="submit" class="btn btn-success btn-block">Guardar</button>
{!! Form::close() !!}

resources/views/personas/edit.blade.php
@extends('personas')
@section('content')
<h4 class="text-center">Editar persona: {{ $persona->nombre }}</h4>
<!--<form action="{{route('personas.update', $persona->id)}}" method ="'DELETE'">-->
{!! Form::model($persona, [ 'route' => ['personas.update', $persona], 'method' => 'PUT']) !!}
<!--</form>-->
@include('personas.partials.fields')
<button type="submit" class="btn btn-success btn-block">Guardar cambios</button>
{!! Form::close() !!}

resources/views/personas/index.blade.php
@extends('personas')
@section('content')
<a class="btn btn-success pull-right" href="{{ url('/personas/create') }}" role="button">Nueva persona</a>
@include('personas.partials.table')
@endsection

resources/views/personas/partials/fields.blade.php
<div class="form-group">
{!! Form::label('nombre', 'Nombre', ['for' => 'nombre'] ) !!}
{!! Form::text('nombre', null , ['class' => 'form-control', 'id' => 'nombre', 'placeholder' => 'Escribe el nombre de la
Persona...' ] ) !!}
</div>

resources/views/personas/partials/table.blade.php
@extends('personas')
@section('content')

<h1 class="text-primary">Añadir Personas</h1>
<a class="btn btn-success pull-right" href="{{ url('/personas/create') }}" role="button">Nueva persona</a>
<table class="table table-bordered table-striped table-hover" id="MyTable">
<thead>
<tr>
<th class="text-center">ID</th>
<th class="text-center">Nombre</th>
<th class="text-center">Acciones</th>
</tr>
</thead>
<tbody>
@foreach($personas as $persona)
<tr>
<td class="text-center">{{ $persona->id }}</td>
<td class="text-center">{{ $persona->nombre }}</td>

{!! Form::open(['route' => ['personas.destroy', $persona->id], 'method' => 'DELETE']) !!}
<form action="{{route('personas.destroy', $persona->id)}}" method ="'DELETE'">
<td class="text-center">

<button type="submit" class="btn btn-danger btn-xs">
<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
</button>
<a href="{{ url('/personas/'.$persona->id.'/edit') }}" class="btn btn-info btn-xs">
<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
</a>
</td>
</form>
{!! Form::close() !!}
</tr>
@endforeach
</tbody>
<tfoot>
<!--<tr>
<th class="text-center">ID</th>
<th class="text-center">Nombre</th>
<th class="text-center">Acciones</th>
</tr>-->
</tfoot>
</table>
<a class="btn btn-primary pull-right" href="{{ url('/') }}" role="button">Volver</a>
@endsection